application: mirrorrr-plus
version: v2
runtime: python
api_version: 1

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: optional

- url: /static/base(\.[0-9])\.css
  static_files: static/base.css
  upload: static/base\.css
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /admin
  login: admin
  script: mirror.py
  secure: optional

- url: /setup 
  script: mirror.py
  secure: optional
  
- url: /cleanup
  login: admin
  script: mirror.py
  secure: optional

- url: /deletesession
  login: admin
  script: mirror.py
  secure: optional
  
- url: /kaboom
  #login: admin
  script: mirror.py
  secure: optional

- url: /.*
  script: mirror.py
  secure: optional
 
error_handlers:
- file: default_error.html

- error_code: over_quota
  file: default_error.html
 
